# File generated by Flopy version 3.3.6 on 07/29/2022 at 12:48:13.
BEGIN attributes
  NAMES  tshead
  METHODS  linearend
END attributes

BEGIN timeseries
       0.00000000     100.00000000
     100.00000000      50.00000000
END timeseries

