name: check warnings - gfortran

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  FC: gfortran

jobs:
  check_warnings:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: bash
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4

      - name: Setup Python
        uses: actions/setup-python@v4.0.0
        with:
          python-version: 3.9

      - name: Setup symbolic links on Linux
        run: |
          sudo ln -fs /usr/bin/gfortran-10 /usr/local/bin/gfortran
          sudo ln -fs /usr/bin/gcc-10 /usr/local/bin/gcc
          sudo ln -fs /usr/bin/g++-10 /usr/local/bin/g++

      - name: Print GNU compiler versions
        run: |
          gfortran --version
          gcc --version
          g++ --version

      - name: Install python packages
        run: |
          .github/common/install-python-std.sh

      - name: Print python package versions
        run: |
          pip list

      - name: Setup modflow
        run: |
          meson setup builddir -Ddebug=false -Dwerror=true

      - name: Build modflow and check for warnings
        run: |
          meson compile -C builddir

  test_night_build_script:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4

      - name: Setup Python
        uses: actions/setup-python@v4.0.0
        with:
          python-version: 3.9

      - name: Setup symbolic links on Linux
        run: |
          sudo ln -fs /usr/bin/gfortran-10 /usr/local/bin/gfortran
          sudo ln -fs /usr/bin/gcc-10 /usr/local/bin/gcc
          sudo ln -fs /usr/bin/g++-10 /usr/local/bin/g++

      - name: Print GNU compiler versions
        run: |
          gfortran --version
          gcc --version
          g++ --version

      - name: Install python packages
        run: |
          .github/common/install-python-std.sh

      - name: Print python package versions
        run: |
          pip list

      - name: Update flopy MODFLOW 6 classes
        working-directory: autotest
        run: |
          python update_flopy.py

      - name: Run nightly build script
        working-directory: distribution
        run: |
          pytest -v -s build_nightly.py

      - name: Move the build zip file
        run: |
          ls -l ./distribution/*
          mv ./distribution/temp_zip/linux.zip ./linux.zip
          ls -l ./
